import { useEffect, useMemo, useState } from 'react'
import './App.css'

const configuredApi = import.meta.env.VITE_API_URL || import.meta.env.VITE_API_BASE_URL || ''
const API = configuredApi.replace(/\/+$/, '').replace(/\/api$/, '')
const restaurantsSeed = [
  { id: 'spice-garden', name: 'Spice Garden', cuisine: ['North Indian', 'Biryani'], rating: 4.8, deliveryTime: '25-30 min', image: 'https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&w=1000&q=85', description: 'Comforting Indian classics, slow-cooked and served warm.' },
  { id: 'pizza-hub', name: 'Pizza Hub', cuisine: ['Pizza', 'Italian'], rating: 4.6, deliveryTime: '20-25 min', image: 'https://images.unsplash.com/photo-1574071318508-1cdbab80d002?auto=format&fit=crop&w=1000&q=85', description: 'Wood-fired pizza, handmade pasta and Italian favourites.' },
  { id: 'wok-express', name: 'Wok Express', cuisine: ['Chinese', 'Asian'], rating: 4.5, deliveryTime: '25-35 min', image: 'https://images.unsplash.com/photo-1612929633738-8fe44f7ec841?auto=format&fit=crop&w=1000&q=85', description: 'Wok-tossed noodles, rice and Asian street food.' },
  { id: 'saffron-house', name: 'Saffron House', cuisine: ['Indian', 'Tandoor'], rating: 4.7, deliveryTime: '30-35 min', image: 'https://images.unsplash.com/photo-1546833999-b9f581a1996d?auto=format&fit=crop&w=1000&q=85', description: 'Smoky tandoor plates and rich regional curries.' },
  { id: 'green-bowl', name: 'Green Bowl', cuisine: ['Healthy', 'Salads'], rating: 4.6, deliveryTime: '15-20 min', image: 'https://images.unsplash.com/photo-1540420773420-3366772f4999?auto=format&fit=crop&w=1000&q=85', description: 'Bright grain bowls, crisp greens and fresh dressings.' },
  { id: 'burger-atelier', name: 'Burger Atelier', cuisine: ['Burgers', 'American'], rating: 4.7, deliveryTime: '20-25 min', image: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&w=1000&q=85', description: 'Stacked burgers, golden fries and house-made sauces.' },
  { id: 'tokyo-table', name: 'Tokyo Table', cuisine: ['Japanese', 'Ramen'], rating: 4.8, deliveryTime: '25-30 min', image: 'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?auto=format&fit=crop&w=1000&q=85', description: 'Comforting ramen, sushi rolls and Japanese small plates.' },
  { id: 'sweet-theory', name: 'Sweet Theory', cuisine: ['Desserts', 'Bakery'], rating: 4.5, deliveryTime: '10-15 min', image: 'https://images.unsplash.com/photo-1578985545062-69928b1d9587?auto=format&fit=crop&w=1000&q=85', description: 'Soft cakes, warm bakes and little moments of sweetness.' },
  { id: 'coastal-curry', name: 'Coastal Curry', cuisine: ['South Indian', 'Seafood'], rating: 4.7, deliveryTime: '30-35 min', image: 'https://images.unsplash.com/photo-1601050690117-94f5f6fa8bd7?auto=format&fit=crop&w=1000&q=85', description: 'Coastal spices, coconut curries and fragrant rice plates.' },
  { id: 'mezze-room', name: 'The Mezze Room', cuisine: ['Mediterranean', 'Middle Eastern'], rating: 4.6, deliveryTime: '25-30 min', image: 'https://images.unsplash.com/photo-1547592180-85f173990554?auto=format&fit=crop&w=1000&q=85', description: 'Fresh mezze, smoky grills and warm flatbreads to share.' },
]
const foodsSeed = [
  { id: 'butter-chicken', name: 'Butter Chicken', category: 'North Indian', restaurant: 'Spice Garden', restaurantId: 'spice-garden', price: 349, rating: 4.8, description: 'Creamy tomato gravy with tender chicken.', image: 'https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?auto=format&fit=crop&w=800&q=85' },
  { id: 'paneer', name: 'Paneer Butter Masala', category: 'North Indian', restaurant: 'Spice Garden', restaurantId: 'spice-garden', price: 299, rating: 4.7, description: 'Soft paneer in a rich, creamy gravy.', image: 'https://images.unsplash.com/photo-1631452180519-c014fe946bc7?auto=format&fit=crop&w=800&q=85' },
  { id: 'pizza', name: 'Margherita Pizza', category: 'Pizza', restaurant: 'Pizza Hub', restaurantId: 'pizza-hub', price: 299, rating: 4.7, description: 'Tomato, mozzarella and fresh basil.', image: 'https://images.unsplash.com/photo-1574071318508-1cdbab80d002?auto=format&fit=crop&w=800&q=85' },
  { id: 'noodles', name: 'Veg Hakka Noodles', category: 'Chinese', restaurant: 'Wok Express', restaurantId: 'wok-express', price: 219, rating: 4.6, description: 'Wok-tossed noodles with crisp vegetables.', image: 'https://images.unsplash.com/photo-1612929633738-8fe44f7ec841?auto=format&fit=crop&w=800&q=85' },
  { id: 'biryani', name: 'Chicken Biryani', category: 'Indian', restaurant: 'Saffron House', restaurantId: 'saffron-house', price: 379, rating: 4.9, description: 'Aromatic rice layered with spiced chicken.', image: 'https://images.unsplash.com/photo-1633945274405-b6c8069047b0?auto=format&fit=crop&w=800&q=85' },
]
const restaurantMenus = {
  'spice-garden': [
    { id: 'spice-tikka', name: 'Tandoori Chicken Tikka', category: 'Starters', restaurant: 'Spice Garden', restaurantId: 'spice-garden', price: 329, rating: 4.8, description: 'Charred chicken, hung yoghurt and warming spices.', image: 'https://images.unsplash.com/photo-1599487488170-d11ec9c172f0?auto=format&fit=crop&w=800&q=85' },
    { id: 'spice-naan', name: 'Garlic Butter Naan', category: 'Breads', restaurant: 'Spice Garden', restaurantId: 'spice-garden', price: 89, rating: 4.7, description: 'Soft tandoor bread finished with garlic butter.', image: 'https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&w=800&q=85' },
  ],
  'pizza-hub': [
    { id: 'pizza-pesto', name: 'Pesto Garden Pizza', category: 'Pizza', restaurant: 'Pizza Hub', restaurantId: 'pizza-hub', price: 389, rating: 4.8, description: 'Basil pesto, mozzarella, tomatoes and greens.', image: 'https://images.unsplash.com/photo-1574071318508-1cdbab80d002?auto=format&fit=crop&w=800&q=85' },
    { id: 'pizza-pasta', name: 'Creamy Herb Pasta', category: 'Italian', restaurant: 'Pizza Hub', restaurantId: 'pizza-hub', price: 319, rating: 4.6, description: 'Silky cream sauce with herbs and parmesan.', image: 'https://images.unsplash.com/photo-1473093295043-cdd812d0e601?auto=format&fit=crop&w=800&q=85' },
  ],
  'wok-express': [
    { id: 'wok-dumplings', name: 'Steamed Veg Dumplings', category: 'Momos', restaurant: 'Wok Express', restaurantId: 'wok-express', price: 229, rating: 4.7, description: 'Delicate dumplings with ginger soy dipping sauce.', image: 'https://images.unsplash.com/photo-1496116218417-1a781b1c416c?auto=format&fit=crop&w=800&q=85' },
    { id: 'wok-rice', name: 'Schezwan Fried Rice', category: 'Rice', restaurant: 'Wok Express', restaurantId: 'wok-express', price: 249, rating: 4.6, description: 'Smoky wok rice tossed with vegetables and chilli.', image: 'https://images.unsplash.com/photo-1512058564366-18510be2db19?auto=format&fit=crop&w=800&q=85' },
  ],
  'saffron-house': [
    { id: 'saffron-kebab', name: 'Saffron Seekh Kebab', category: 'Tandoor', restaurant: 'Saffron House', restaurantId: 'saffron-house', price: 349, rating: 4.8, description: 'Juicy minced kebabs with mint chutney.', image: 'https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=800&q=85' },
    { id: 'saffron-kheer', name: 'Cardamom Kheer', category: 'Desserts', restaurant: 'Saffron House', restaurantId: 'saffron-house', price: 149, rating: 4.5, description: 'Slow-cooked rice pudding with pistachio.', image: 'https://images.unsplash.com/photo-1599785209707-a456fc1337bb?auto=format&fit=crop&w=800&q=85' },
  ],
  'green-bowl': [
    { id: 'green-avocado', name: 'Avocado Grain Bowl', category: 'Healthy', restaurant: 'Green Bowl', restaurantId: 'green-bowl', price: 299, rating: 4.7, description: 'Avocado, grains, greens and citrus dressing.', image: 'https://images.unsplash.com/photo-1540420773420-3366772f4999?auto=format&fit=crop&w=800&q=85' },
    { id: 'green-smoothie', name: 'Mango Green Smoothie', category: 'Drinks', restaurant: 'Green Bowl', restaurantId: 'green-bowl', price: 179, rating: 4.6, description: 'Fresh mango, spinach and coconut water.', image: 'https://images.unsplash.com/photo-1502741224143-90386d7f8c82?auto=format&fit=crop&w=800&q=85' },
  ],
  'burger-atelier': [
    { id: 'atelier-cheese', name: 'Smoky Cheese Burger', category: 'Burgers', restaurant: 'Burger Atelier', restaurantId: 'burger-atelier', price: 329, rating: 4.9, description: 'Crispy edges, aged cheddar and smoky sauce.', image: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&w=800&q=85' },
    { id: 'atelier-fries', name: 'Truffle Parmesan Fries', category: 'Sides', restaurant: 'Burger Atelier', restaurantId: 'burger-atelier', price: 189, rating: 4.7, description: 'Golden fries with truffle oil and parmesan.', image: 'https://images.unsplash.com/photo-1573080496219-bb080dd4f877?auto=format&fit=crop&w=800&q=85' },
  ],
  'tokyo-table': [
    { id: 'tokyo-ramen', name: 'Miso Ramen', category: 'Ramen', restaurant: 'Tokyo Table', restaurantId: 'tokyo-table', price: 399, rating: 4.8, description: 'Rich miso broth, noodles, corn and greens.', image: 'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?auto=format&fit=crop&w=800&q=85' },
    { id: 'tokyo-sushi', name: 'Salmon Sushi Roll', category: 'Sushi', restaurant: 'Tokyo Table', restaurantId: 'tokyo-table', price: 429, rating: 4.7, description: 'Fresh salmon, avocado and seasoned rice.', image: 'https://images.unsplash.com/photo-1579871494447-9811cf80d66c?auto=format&fit=crop&w=800&q=85' },
  ],
  'sweet-theory': [
    { id: 'sweet-brownie', name: 'Warm Fudge Brownie', category: 'Desserts', restaurant: 'Sweet Theory', price: 199, rating: 4.8, description: 'Dark chocolate brownie with a soft centre.', image: 'https://images.unsplash.com/photo-1578985545062-69928b1d9587?auto=format&fit=crop&w=800&q=85' },
    { id: 'sweet-cheesecake', name: 'Berry Cheesecake', category: 'Desserts', restaurant: 'Sweet Theory', price: 249, rating: 4.7, description: 'Creamy cheesecake with bright berry compote.', image: 'https://images.unsplash.com/photo-1565958011703-44f9829ba187?auto=format&fit=crop&w=800&q=85' },
  ],
}
const completeMenuTemplates = [
  ['Signature Starter', 'Starters', 179, 'A generous plate of house-seasoned bites.', 'https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=800&q=85'],
  ['House Special', 'Recommended', 299, 'The dish everyone comes back for.', 'https://images.unsplash.com/photo-1547592180-85f173990554?auto=format&fit=crop&w=800&q=85'],
  ['Classic Comfort Bowl', 'Mains', 269, 'Warm, satisfying and full of flavour.', 'https://images.unsplash.com/photo-1512058564366-18510be2db19?auto=format&fit=crop&w=800&q=85'],
  ['Garden Fresh Salad', 'Healthy', 229, 'Crisp greens with a bright house dressing.', 'https://images.unsplash.com/photo-1540420773420-3366772f4999?auto=format&fit=crop&w=800&q=85'],
  ['Spiced Rice Plate', 'Rice', 319, 'Fragrant rice layered with aromatic spices.', 'https://images.unsplash.com/photo-1633945274405-b6c8069047b0?auto=format&fit=crop&w=800&q=85'],
  ['Charcoal Grill Platter', 'Grills', 399, 'Smoky grilled favourites served hot.', 'https://images.unsplash.com/photo-1599487488170-d11ec9c172f0?auto=format&fit=crop&w=800&q=85'],
  ['Crispy Golden Fries', 'Sides', 149, 'Golden, crisp and perfect for sharing.', 'https://images.unsplash.com/photo-1573080496219-bb080dd4f877?auto=format&fit=crop&w=800&q=85'],
  ['Handmade Dumplings', 'Momos', 219, 'Delicate parcels with a savoury dipping sauce.', 'https://images.unsplash.com/photo-1496116218417-1a781b1c416c?auto=format&fit=crop&w=800&q=85'],
  ['Creamy Pasta', 'Italian', 329, 'Silky sauce, herbs and freshly grated cheese.', 'https://images.unsplash.com/photo-1473093295043-cdd812d0e601?auto=format&fit=crop&w=800&q=85'],
  ['Wood Fired Flatbread', 'Breads', 289, 'Hand-stretched, baked and finished with herbs.', 'https://images.unsplash.com/photo-1574071318508-1cdbab80d002?auto=format&fit=crop&w=800&q=85'],
  ['Fresh Fruit Cooler', 'Drinks', 129, 'Chilled seasonal fruit with a refreshing finish.', 'https://images.unsplash.com/photo-1502741224143-90386d7f8c82?auto=format&fit=crop&w=800&q=85'],
  ['Mango Lassi', 'Drinks', 139, 'Creamy mango yoghurt drink with cardamom.', 'https://images.unsplash.com/photo-1577805947697-89e18249d767?auto=format&fit=crop&w=800&q=85'],
  ['Warm Chocolate Cake', 'Desserts', 199, 'Soft chocolate cake with a rich centre.', 'https://images.unsplash.com/photo-1578985545062-69928b1d9587?auto=format&fit=crop&w=800&q=85'],
  ['Berry Cheesecake', 'Desserts', 249, 'Creamy cheesecake with bright berry compote.', 'https://images.unsplash.com/photo-1565958011703-44f9829ba187?auto=format&fit=crop&w=800&q=85'],
  ['House Chai', 'Drinks', 99, 'Fragrant tea brewed with warming spices.', 'https://images.unsplash.com/photo-1544787219-7f47ccb76574?auto=format&fit=crop&w=800&q=85'],
]
const completeRestaurantMenus = Object.fromEntries(restaurantsSeed.map((restaurant) => [restaurant.id, completeMenuTemplates.map(([name, category, price, description, image], index) => ({ id: `${restaurant.id}-menu-${index}`, name, category, price, rating: 4.5 + (index % 5) / 10, description, image, restaurant: restaurant.name, restaurantId: restaurant.id }))]))
const categoryIcons = { All: '✦', Pizza: '🍕', Burgers: '🍔', Chicken: '🍗', Chinese: '🍜', Momos: '🥟', Biryani: '🍛', Healthy: '🥗', Desserts: '🍰' }
const offers = [
  { code: 'FIRSTBITE', title: '50% OFF', detail: 'Up to ₹150 on your first order', tone: 'lime' },
  { code: 'FREEDEL', title: 'FREE DELIVERY', detail: 'On orders above ₹499', tone: 'orange' },
  { code: 'WEEKEND', title: 'BUY 1 GET 1', detail: 'Weekend specials from local kitchens', tone: 'dark' },
]
const notifications = [
  { icon: '🍳', title: 'Your order is being prepared', detail: 'Miso Ramen is getting ready', time: '2 min ago' },
  { icon: '🎟️', title: '₹100 OFF on your next order', detail: 'Use code WELCOME before it expires', time: '1 hour ago' },
  { icon: '♥', title: 'Your favorite restaurant is open', detail: 'Spice Garden is accepting orders', time: 'Yesterday' },
]
const catalogPrices = { 'margherita pizza': 299, 'classic burger': 329, 'spicy noodles': 249, 'chicken biryani': 379, 'chocolate cake': 199, 'green salad bowl': 249 }
const normalizeFood = (food) => ({ ...food, price: catalogPrices[String(food.name || '').trim().toLowerCase()] || (Number(food.price) < 100 ? Math.round(Number(food.price) * 20) : Number(food.price)) })
const idOf = (value) => value?._id || value?.id
const money = (value) => `₹${Math.round(Number(value) || 0)}`
const foodImages = {
  'butter chicken': 'https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?auto=format&fit=crop&w=800&q=85',
  'paneer butter masala': 'https://images.unsplash.com/photo-1631452180519-c014fe946bc7?auto=format&fit=crop&w=800&q=85',
  'margherita pizza': 'https://images.unsplash.com/photo-1574071318508-1cdbab80d002?auto=format&fit=crop&w=800&q=85',
  'veg hakka noodles': 'https://images.unsplash.com/photo-1612929633738-8fe44f7ec841?auto=format&fit=crop&w=800&q=85',
  'classic burger': 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&w=800&q=85',
  'spicy noodles': 'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?auto=format&fit=crop&w=800&q=85',
  'chicken biryani': 'https://images.unsplash.com/photo-1633945274405-b6c8069047b0?auto=format&fit=crop&w=800&q=85',
  'chocolate cake': 'https://images.unsplash.com/photo-1578985545062-69928b1d9587?auto=format&fit=crop&w=800&q=85',
  'green salad bowl': 'https://images.unsplash.com/photo-1540420773420-3366772f4999?auto=format&fit=crop&w=800&q=85',
}
const imageForFood = (food) => { const name = String(food.name || '').trim().toLowerCase(); const template = completeMenuTemplates?.find((item) => item[0].toLowerCase() === name); return (/^https?:\/\//i.test(food.image || '') ? food.image : foodImages[name] || template?.[4]) || fallbackImage }
const fallbackImage = 'data:image/svg+xml,%3Csvg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 800 500"%3E%3Crect width="800" height="500" fill="%23345846"/%3E%3Ccircle cx="400" cy="225" r="92" fill="%23d7ed72"/%3E%3Cpath d="M350 225h100M400 175v100" stroke="%23345846" stroke-width="18" stroke-linecap="round"/%3E%3Ctext x="400" y="390" text-anchor="middle" fill="white" font-family="sans-serif" font-size="30"%3EMorsel%3C/text%3E%3C/svg%3E'
const handleImageError = (event) => { event.currentTarget.onerror = null; event.currentTarget.src = fallbackImage }
async function api(path, options = {}) {
  const token = localStorage.getItem('morsel-token')
  let response
  try {
    response = await fetch(`${API}/api${path}`, { ...options, headers: { 'Content-Type': 'application/json', ...(token ? { Authorization: `Bearer ${token}` } : {}), ...(options.headers || {}) } })
  } catch {
    throw new Error('Cannot connect to the backend. Start it with npm start and try again.')
  }
  const data = await response.json().catch(() => ({}))
  if (!response.ok) throw new Error(data.message || 'Something went wrong')
  return data
}

export default function App() {
  const [view, setView] = useState('home')
  const [restaurants, setRestaurants] = useState(restaurantsSeed)
  const [foods, setFoods] = useState(foodsSeed)
  const [activeRestaurant, setActiveRestaurant] = useState(null)
  const [cart, setCart] = useState(() => JSON.parse(localStorage.getItem('morsel-cart') || '[]'))
  const [user, setUser] = useState(() => JSON.parse(localStorage.getItem('morsel-user') || 'null'))
  const [orders, setOrders] = useState([])
  const [search, setSearch] = useState('')
  const [location, setLocation] = useState('Delivering to your location')
  const [recentSearches, setRecentSearches] = useState(() => JSON.parse(localStorage.getItem('morsel-searches') || '[]'))
  const [favorites, setFavorites] = useState(() => JSON.parse(localStorage.getItem('morsel-favorites') || '[]'))
  const [darkMode, setDarkMode] = useState(() => localStorage.getItem('morsel-theme') === 'dark')
  const [cuisine, setCuisine] = useState('All')
  const [sort, setSort] = useState('rating')
  const [coupon, setCoupon] = useState('')
  const [couponApplied, setCouponApplied] = useState(false)
  const [authOpen, setAuthOpen] = useState(false)
  const [authMode, setAuthMode] = useState('login')
  const [authBusy, setAuthBusy] = useState(false)
  const [notice, setNotice] = useState('')
  const [points, setPoints] = useState(() => Number(localStorage.getItem('morsel-points') || 1250))

  useEffect(() => { localStorage.setItem('morsel-searches', JSON.stringify(recentSearches)) }, [recentSearches])
  useEffect(() => { localStorage.setItem('morsel-favorites', JSON.stringify(favorites)) }, [favorites])
  useEffect(() => { localStorage.setItem('morsel-theme', darkMode ? 'dark' : 'light') }, [darkMode])
  useEffect(() => { localStorage.setItem('morsel-points', String(points)) }, [points])
  useEffect(() => { setCart((items) => items.map((item) => { const match = foods.find((food) => String(food.name).toLowerCase() === String(item.name).toLowerCase()); return match ? { ...item, foodId: idOf(match), price: Number(match.price), image: imageForFood(match) } : item })) }, [foods])

  useEffect(() => { localStorage.setItem('morsel-cart', JSON.stringify(cart)) }, [cart])
  useEffect(() => { Promise.all([api('/restaurants'), api('/foods')]).then(([rs, fs]) => { if (rs?.length) setRestaurants(rs); if (fs?.length) setFoods(fs.map(normalizeFood)) }).catch(() => {}) }, [])
  useEffect(() => { if (user) api('/orders').then(setOrders).catch(() => {}) }, [user])

  const cuisines = useMemo(() => ['All', ...new Set(restaurants.flatMap((item) => item.cuisine || []))], [restaurants])
  const visibleRestaurants = useMemo(() => restaurants.filter((item) => `${item.name} ${(item.cuisine || []).join(' ')}`.toLowerCase().includes(search.toLowerCase()) && (cuisine === 'All' || item.cuisine?.includes(cuisine))).sort((a, b) => sort === 'rating' ? (b.rating || 0) - (a.rating || 0) : String(a.deliveryTime).localeCompare(String(b.deliveryTime))), [restaurants, search, cuisine, sort])
  const visibleFoods = useMemo(() => foods.filter((item) => `${item.name} ${item.category} ${item.restaurant || ''}`.toLowerCase().includes(search.toLowerCase())), [foods, search])
  const subtotal = cart.reduce((sum, item) => sum + item.price * item.quantity, 0)
  const discount = couponApplied ? Math.min(Math.round(subtotal * (coupon.toUpperCase() === 'FOODIE50' ? .5 : .2)), coupon.toUpperCase() === 'FOODIE50' ? 150 : 100) : 0
  const pricing = { subtotal, discount, delivery: subtotal ? (subtotal >= 499 ? 0 : 40) : 0, platform: subtotal ? 8 : 0, tax: Math.round((subtotal - discount) * .05) }
  pricing.total = pricing.subtotal + pricing.delivery + pricing.platform + pricing.tax - pricing.discount
  const go = (next) => { setView(next); window.scrollTo({ top: 0, behavior: 'smooth' }) }
  const runSearch = (value) => { setSearch(value); if (value.trim()) setRecentSearches((items) => [value.trim(), ...items.filter((item) => item.toLowerCase() !== value.trim().toLowerCase())].slice(0, 5)) }
  const toggleFavorite = (id) => setFavorites((items) => items.includes(id) ? items.filter((item) => item !== id) : [...items, id])
  const copyReferral = async () => { await navigator.clipboard?.writeText('MORSEL-DABLOO'); setNotice('Referral code copied') }
  const addToCart = (food) => { const foodId = idOf(food); setCart((items) => { const existing = items.find((item) => item.foodId === foodId); return existing ? items.map((item) => item.foodId === foodId ? { ...item, quantity: item.quantity + 1 } : item) : [...items, { foodId, name: food.name, image: imageForFood(food), price: Number(food.price), quantity: 1 }] }); setNotice(`${food.name} added to cart`); setTimeout(() => setNotice(''), 1800) }
  const updateQuantity = (foodId, amount) => setCart((items) => items.map((item) => item.foodId === foodId ? { ...item, quantity: item.quantity + amount } : item).filter((item) => item.quantity > 0))
  const openRestaurant = async (item) => { setActiveRestaurant(item); go('restaurant'); if (!/^[a-f0-9]{24}$/i.test(String(idOf(item)))) return; try { const data = await api(`/restaurants/${idOf(item)}`); if (data.restaurant) setActiveRestaurant(data.restaurant); if (data.menu?.length) setFoods((current) => [...current.filter((food) => !data.menu.some((entry) => idOf(entry) === idOf(food))), ...data.menu]) } catch {} }
  const signIn = async (event) => { event.preventDefault(); if (authBusy) return; setAuthBusy(true); const form = new FormData(event.currentTarget); try { const data = await api(`/auth/${authMode}`, { method: 'POST', body: JSON.stringify(Object.fromEntries(form)) }); localStorage.setItem('morsel-token', data.token); localStorage.setItem('morsel-user', JSON.stringify(data.user)); setUser(data.user); setAuthOpen(false); setNotice(`Welcome, ${data.user.name}`) } catch (error) { setNotice(error.message) } finally { setAuthBusy(false) } }
  const placeOrder = async (event) => { event.preventDefault(); if (!user) return setAuthOpen(true); const form = new FormData(event.currentTarget); const paymentMethod = form.get('paymentMethod'); const payload = { items: cart.map((item) => ({ foodId: item.foodId, quantity: item.quantity })), deliveryAddress: { street: form.get('street'), city: form.get('city'), state: form.get('state'), zipCode: form.get('zipCode'), country: 'India' }, phone: form.get('phone'), notes: form.get('notes'), paymentMethod, couponCode: couponApplied ? coupon.toUpperCase() : '' }; const finish = (order) => { setCart([]); setOrders((current) => [order, ...current]); go('orders'); setNotice('Order placed successfully') }; try { const order = await api('/orders', { method: 'POST', body: JSON.stringify(payload) }); const paymentData = await api('/payments/create', { method: 'POST', body: JSON.stringify({ orderId: order._id, provider: paymentMethod === 'cash' ? 'cash' : 'razorpay' }) }); if (paymentMethod === 'cash') return finish(order); if (!paymentData.razorpayOrder || !paymentData.keyId) throw new Error('Online payment is not configured'); await new Promise((resolve, reject) => { const script = document.createElement('script'); script.src = 'https://checkout.razorpay.com/v1/checkout.js'; script.onload = resolve; script.onerror = () => reject(new Error('Unable to load Razorpay')); document.body.appendChild(script) }); const checkout = new window.Razorpay({ key: paymentData.keyId, amount: paymentData.razorpayOrder.amount, currency: 'INR', name: 'Morsel', description: 'Morsel food order', order_id: paymentData.razorpayOrder.id, prefill: { name: user.name, email: user.email, contact: payload.phone }, handler: async (response) => { try { await api(`/payments/${paymentData.payment._id}/verify`, { method: 'POST', body: JSON.stringify(response) }); finish(order) } catch (error) { setNotice(error.message) } } }); checkout.open() } catch (error) { setNotice(error.message) } }

  return <div className={`app ${darkMode ? 'dark' : ''}`}><header className="topbar"><button className="brand" onClick={() => go('home')}><span className="brand-mark">M</span><span><b>Morsel</b><small>good food, good mood</small></span></button><button className="location-button" onClick={() => setLocation(location === 'Delivering to your location' ? 'Home, New Delhi' : 'Delivering to your location')}>⌖ <span>{location}</span></button><div className="search"><span>⌕</span><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search pizza, biryani, burgers..." /></div><nav><button className="theme-button" onClick={() => setDarkMode(!darkMode)} aria-label="Toggle dark mode">{darkMode ? '☀' : '☾'}</button><button onClick={() => go('restaurants')}>Restaurants</button><button onClick={() => go('orders')}>Orders</button><button onClick={() => user ? go('profile') : setAuthOpen(true)}>{user ? user.name : 'Sign in'}</button><button className="cart-link" onClick={() => go('cart')}>Cart <b>{cart.reduce((sum, item) => sum + item.quantity, 0)}</b></button></nav></header>
    {notice && <div className="toast">{notice}</div>}
    {view === 'home' && <Home onRestaurants={() => go('restaurants')} restaurants={restaurants} foods={foods} openRestaurant={openRestaurant} addToCart={addToCart} cuisines={cuisines} setCuisine={setCuisine} setSearch={runSearch} recentSearches={recentSearches} favorites={favorites} toggleFavorite={toggleFavorite} />}
    {view === 'restaurants' && <main className="content"><Heading eyebrow="DISCOVER" title="Restaurants near you" text={`${visibleRestaurants.length} places serving your favourites`} /><div className="filters"><select value={sort} onChange={(event) => setSort(event.target.value)}><option value="rating">Top rated</option><option value="delivery">Fastest delivery</option></select>{cuisines.map((item) => <button className={cuisine === item ? 'active' : ''} key={item} onClick={() => setCuisine(item)}>{item}</button>)}</div>{!search && recentSearches.length > 0 && <div className="search-history"><b>Recent searches</b>{recentSearches.map((item) => <button key={item} onClick={() => runSearch(item)}>{item}</button>)}</div>}<div className="restaurant-grid">{visibleRestaurants.map((item) => <RestaurantCard key={idOf(item)} item={item} open={openRestaurant} favorite={favorites.includes(idOf(item))} toggleFavorite={toggleFavorite} />)}</div></main>}
    {view === 'restaurant' && activeRestaurant && <RestaurantDetail item={activeRestaurant} foods={(completeRestaurantMenus[idOf(activeRestaurant)] || restaurantMenus[idOf(activeRestaurant)] || []).map((menuItem) => foods.find((food) => String(food.name).toLowerCase() === String(menuItem.name).toLowerCase()) || menuItem)} addToCart={addToCart} back={() => go('restaurants')} />}
    {view === 'cart' && <Cart cart={cart} update={updateQuantity} coupon={coupon} setCoupon={setCoupon} apply={() => setCouponApplied(['FOODIE50', 'WELCOME'].includes(coupon.toUpperCase()))} applied={couponApplied} pricing={pricing} checkout={() => go('checkout')} />}
    {view === 'checkout' && <Checkout user={user} placeOrder={placeOrder} pricing={pricing} />}
    {view === 'orders' && <Orders orders={orders} signIn={() => setAuthOpen(true)} />}
    {view === 'profile' && <Profile user={user} logout={() => { localStorage.clear(); setUser(null); go('home') }} onOrders={() => go('orders')} onAddresses={() => go('addresses')} onFavorites={() => go('favorites')} onHelp={() => go('help')} />}
    {view === 'addresses' && user && <Addresses back={() => go('profile')} />}
    {view === 'favorites' && <Favorites restaurants={restaurants.filter((item) => favorites.includes(idOf(item)))} foods={foods.filter((item) => favorites.includes(idOf(item)))} back={() => go('profile')} openRestaurant={openRestaurant} addToCart={addToCart} />}
    {view === 'help' && <HelpSupport back={() => go('profile')} />}
    <footer><b>Morsel</b><span>Thoughtful food, delivered with care.</span><span>© 2026 Morsel</span></footer><nav className="mobile-nav" aria-label="Mobile navigation"><button onClick={() => go('home')}><span>⌂</span>Home</button><button onClick={() => go('restaurants')}><span>⌕</span>Search</button><button onClick={() => go('favorites')}><span>♥</span>Favorites</button><button onClick={() => go('cart')}><span>🛒</span>Cart{cart.length > 0 && <b>{cart.reduce((sum, item) => sum + item.quantity, 0)}</b>}</button><button onClick={() => user ? go('profile') : setAuthOpen(true)}><span>●</span>Profile</button></nav>
    {authOpen && <div className="modal" onClick={() => setAuthOpen(false)}><form className="auth-card" onClick={(event) => event.stopPropagation()} onSubmit={signIn}><button type="button" className="close" onClick={() => setAuthOpen(false)}>×</button><span className="eyebrow">{authMode === 'login' ? 'WELCOME BACK' : 'JOIN MORSEL'}</span><h2>{authMode === 'login' ? 'Sign in to order' : 'Create your account'}</h2>{authMode === 'register' && <input name="name" placeholder="Full name" required />}{authMode === 'register' && <input name="phone" placeholder="Phone number" required />}<input name="email" type="email" placeholder="Email address" required /><input name="password" type="password" placeholder="Password" minLength="6" required /><button className="primary" disabled={authBusy}>{authBusy ? 'Please wait...' : authMode === 'login' ? 'Sign in' : 'Create account'}</button><p>{authMode === 'login' ? 'New to Morsel?' : 'Already have an account?'} <button type="button" className="text-button" onClick={() => setAuthMode(authMode === 'login' ? 'register' : 'login')}>{authMode === 'login' ? 'Register' : 'Sign in'}</button></p></form></div>}
  </div>
}

function Heading({ eyebrow, title, text }) { return <div className="heading"><span className="eyebrow">{eyebrow}</span><h1>{title}</h1><p>{text}</p></div> }
function Home({ onRestaurants, restaurants, foods, openRestaurant, addToCart, cuisines, setCuisine, setSearch, recentSearches, favorites, toggleFavorite }) { const homeFoods = [...foods, ...Object.values(completeRestaurantMenus).flat()].filter((food, index, list) => list.findIndex((entry) => String(entry.name).toLowerCase() === String(food.name).toLowerCase()) === index).slice(0, 10); return <main><section className="hero"><div><span className="eyebrow">GOOD FOOD. GREAT MOOD.</span><h1>Good food finds<br /><i>you.</i></h1><p>Discover the best food and restaurants near you, delivered with a little more care.</p><div className="hero-search"><span>⌕</span><input placeholder="Search pizza, biryani, burgers..." onChange={(event) => setSearch(event.target.value)} /><button onClick={onRestaurants}>Search</button></div><button className="primary" onClick={onRestaurants}>Order now <span>→</span></button></div><div className="hero-art"><img src="https://images.unsplash.com/photo-1504674900247-0877df9cc836?auto=format&fit=crop&w=1200&q=85" alt="A table full of food" onError={handleImageError} /><div className="hero-food-stack">{homeFoods.slice(0, 3).map((food, index) => <div className={`hero-food hero-food-${index}`} key={idOf(food)}><img src={imageForFood(food)} alt={food.name} onError={handleImageError} /><span>{food.name}</span></div>)}</div></div></section><section className="content"><div className="category-strip"><div><span className="eyebrow">WHAT ARE YOU CRAVING?</span><h2>Order by category</h2></div><div className="category-list">{['All', ...cuisines.filter((item) => item !== 'All'), 'Burgers', 'Chinese', 'Desserts'].filter((item, index, list) => list.indexOf(item) === index).slice(0, 8).map((item) => <button key={item} onClick={() => { setCuisine(item); onRestaurants() }}>{categoryIcons[item] || '•'}<span>{item}</span></button>)}</div></div><Heading eyebrow="LOCAL FAVOURITES" title="Made for your mood" text="A few places we think you'll love." /><div className="restaurant-grid">{restaurants.slice(0, 8).map((item) => <RestaurantCard key={idOf(item)} item={item} open={openRestaurant} favorite={favorites.includes(idOf(item))} toggleFavorite={toggleFavorite} />)}</div><div className="section-head"><div><span className="eyebrow">QUICK BITES</span><h2>Popular right now</h2></div><button className="text-button" onClick={onRestaurants}>See all →</button></div><div className="food-grid">{homeFoods.map((food) => <FoodCard key={idOf(food)} food={food} add={addToCart} />)}</div>{recentSearches.length > 0 && <div className="search-history home-history"><b>Search again</b>{recentSearches.slice(0, 4).map((item) => <button key={item} onClick={() => setSearch(item)}>{item}</button>)}</div>}</section></main> }
function RestaurantCard({ item, open, favorite, toggleFavorite }) { return <article className="restaurant-card" onClick={() => open(item)}><div className="restaurant-image"><img src={item.image} alt={item.name} onError={handleImageError} /><button className="favorite" aria-label="Save restaurant" onClick={(event) => { event.stopPropagation(); toggleFavorite?.(idOf(item)) }}>{favorite ? '♥' : '♡'}</button><span className="discount-badge">{Number(item.rating) >= 4.7 ? 'Popular' : '20% off'}</span></div><div><div className="card-line"><h3>{item.name}</h3><span className="rating">★ {Number(item.rating || 0).toFixed(1)}</span></div><p>{(item.cuisine || []).join(' · ')} · ₹₹</p><small>{item.deliveryTime || '30 min'} · delivers to you</small></div></article> }
function FoodCard({ food, add }) { return <article className="food-card"><img src={imageForFood(food)} alt={food.name} onError={handleImageError} /><div><div className="card-line"><h3>{food.name}</h3><span className="rating">★ {Number(food.rating || 0).toFixed(1)}</span></div><p>{food.description}</p><div className="food-bottom"><strong>{money(food.price)}</strong><button onClick={() => add(food)}>Add</button></div></div></article> }
function RestaurantDetail({ item, foods, addToCart, back }) { const [menuSearch, setMenuSearch] = useState(''); const visibleFoods = foods.filter((food) => `${food.name} ${food.category || ''}`.toLowerCase().includes(menuSearch.toLowerCase())); return <main className="content"><button className="back" onClick={back}>← All restaurants</button><section className="detail-hero"><img src={item.image} alt={item.name} onError={handleImageError} /><div><span className="eyebrow">{(item.cuisine || []).join(' · ').toUpperCase()}</span><h1>{item.name}</h1><p>{item.description || 'Made fresh, just for you.'}</p><span className="rating">★ {Number(item.rating || 0).toFixed(1)} · {item.deliveryTime || '30 min'} · ₹₹</span></div></section><div className="menu-toolbar"><div><span className="eyebrow">THE MENU</span><h2>Choose your comfort</h2></div><div className="menu-search">⌕<input value={menuSearch} onChange={(event) => setMenuSearch(event.target.value)} placeholder="Search this menu" /></div></div><div className="menu-section-label">Recommended <span>{visibleFoods.length} dishes</span></div><div className="food-grid">{visibleFoods.map((food) => <FoodCard key={idOf(food)} food={food} add={addToCart} />)}</div></main> }
function Bill({ pricing }) { return <div className="bill"><h3>Order summary</h3><p><span>Item total</span><b>{money(pricing.subtotal)}</b></p><p><span>Delivery</span><b>{pricing.delivery ? money(pricing.delivery) : 'FREE'}</b></p><p><span>Platform fee</span><b>{money(pricing.platform)}</b></p><p><span>Taxes</span><b>{money(pricing.tax)}</b></p>{pricing.discount > 0 && <p className="discount"><span>Coupon discount</span><b>-{money(pricing.discount)}</b></p>}<div className="total"><span>To pay</span><strong>{money(pricing.total)}</strong></div></div> }
function Cart({ cart, update, coupon, setCoupon, apply, applied, pricing, checkout }) { return <main className="content narrow"><Heading eyebrow="YOUR ORDER" title="Your cart" text={`${cart.length} ${cart.length === 1 ? 'item' : 'items'} selected`} />{cart.length === 0 ? <div className="empty"><span>◌</span><h2>Your cart is waiting</h2><p>Add something delicious to get started.</p></div> : <div className="cart-layout"><div>{cart.map((item) => <div className="cart-row" key={item.foodId}><img src={imageForFood(item)} alt={item.name} onError={handleImageError} /><div><h3>{item.name}</h3><strong>{money(item.price)}</strong></div><div className="quantity"><button onClick={() => update(item.foodId, -1)}>−</button><span>{item.quantity}</span><button onClick={() => update(item.foodId, 1)}>+</button></div></div>)}<div className="coupon"><input value={coupon} onChange={(event) => setCoupon(event.target.value)} placeholder="Coupon code" /><button onClick={apply}>Apply</button></div>{applied && <small className="success">Coupon applied. Nice choice.</small>}</div><div><Bill pricing={pricing} /><button className="primary wide" onClick={checkout}>Continue to checkout <span>→</span></button></div></div>}</main> }
function Checkout({ user, placeOrder, pricing }) { const [step, setStep] = useState(1); const [paymentChoice, setPaymentChoice] = useState('cash'); return <main className="content narrow"><Heading eyebrow="SECURE CHECKOUT" title="Almost there." text="Your meal is one confident click away." /><div className="checkout-steps"><span className={step >= 1 ? 'active' : ''}>1 Address</span><span className={step >= 2 ? 'active' : ''}>2 Payment</span><span className={step >= 3 ? 'active' : ''}>3 Review</span></div><form className="checkout-layout" onSubmit={placeOrder}><div className="checkout-form"><div className="payment-panel"><div className="panel-heading"><div><span className="eyebrow">DELIVERY DETAILS</span><h3>Where should we bring it?</h3></div><span className="secure-badge">✓ Secure</span></div><label>Phone number<input name="phone" defaultValue={user?.phone || ''} required /></label><label>Address<input name="street" placeholder="House number and street" required /></label><div className="two"><label>City<input name="city" placeholder="City" required /></label><label>State<input name="state" placeholder="State" required /></label></div><div className="two"><label>PIN code<input name="zipCode" placeholder="110001" required /></label><label>Instructions<input name="notes" placeholder="Ring the bell, leave at door..." /></label></div></div><fieldset className="payment-panel"><legend>Choose payment</legend><div className="payment-options"><label className={paymentChoice === 'cash' ? 'payment-option selected' : 'payment-option'}><input type="radio" name="paymentMethod" value="cash" checked={paymentChoice === 'cash'} onChange={() => setPaymentChoice('cash')} /><span>💵</span><b>Cash on Delivery</b><small>Pay when your order arrives</small></label><label className={paymentChoice === 'razorpay' ? 'payment-option selected' : 'payment-option'}><input type="radio" name="paymentMethod" value="razorpay" checked={paymentChoice === 'razorpay'} onChange={() => setPaymentChoice('razorpay')} /><span>💳</span><b>Card / UPI</b><small>Secure payment via Razorpay</small></label></div></fieldset><button type="button" className="text-button" onClick={() => setStep((current) => current === 3 ? 1 : current + 1)}>Review step {step === 3 ? 'complete' : '→'}</button><button className="primary wide">Place order <span>{money(pricing.total)} →</span></button></div><Bill pricing={pricing} /></form></main> }
function Orders({ orders, signIn }) { return <main className="content narrow"><Heading eyebrow="YOUR JOURNEY" title="Order history" text="Every good meal has a story." />{!orders.length ? <div className="empty"><h2>No orders yet</h2><p>Once you order, your meals will appear here.</p><button className="primary" onClick={signIn}>Sign in to see orders</button></div> : <div className="orders">{orders.map((order) => <article key={order._id}><div><span className="eyebrow">ORDER #{String(order._id).slice(-6).toUpperCase()}</span><h3>{order.items?.map((item) => `${item.name} ×${item.quantity}`).join(', ')}</h3><div className="order-tracker"><span className="done">✓ Placed</span><span className="done">✓ Preparing</span><span className={order.status === 'delivered' ? 'done' : 'current'}>{order.status === 'delivered' ? '✓ Delivered' : '● Out for delivery'}</span></div></div><strong>{money(order.totalAmount)}</strong><span className="status">{order.status}</span></article>)}</div>}</main> }
function Profile({ user, logout, onOrders, onAddresses, onFavorites, onHelp }) { const points = Number(localStorage.getItem('morsel-points') || 1250); const copyCode = () => { navigator.clipboard?.writeText('MORSEL-DABLOO'); }; return <main className="content narrow"><Heading eyebrow="ACCOUNT" title={`Hello, ${user?.name?.split(' ')[0] || 'Morsel member'}`} text="Your details, kept in one place." /><div className="profile"><span className="avatar">{user?.name?.[0] || 'M'}</span><h2>{user?.name || 'Morsel member'}</h2><p>{user?.email}</p><p>{user?.phone || 'Add a phone number at checkout.'}</p><div className="rewards-card"><span className="eyebrow">★ MORSEL REWARDS</span><strong>{points.toLocaleString()}</strong><small>points · 250 more points → ₹100 OFF</small><div className="rewards-progress"><i style={{ width: `${Math.min(100, (points % 1500) / 15)}%` }} /></div></div><div className="referral-card"><div><span className="eyebrow">INVITE FRIENDS</span><h3>Give ₹100, get ₹100</h3><small>MORSEL-DABLOO</small></div><button onClick={copyCode}>Copy code</button></div><div className="profile-links"><button onClick={onOrders}>My orders</button><button onClick={onAddresses}>Saved addresses</button><button onClick={onFavorites}>Favorites ♥</button><button onClick={onHelp}>Help & support</button></div><button className="text-button" onClick={logout}>Sign out</button></div></main> }
function Addresses({ back }) { const [addresses, setAddresses] = useState([]); const [saving, setSaving] = useState(false); const [message, setMessage] = useState(''); useEffect(() => { api('/auth/me').then((data) => setAddresses(data.user?.addresses || [])).catch((error) => setMessage(error.message)) }, []); const save = async (event) => { event.preventDefault(); setSaving(true); const form = new FormData(event.currentTarget); try { const data = await api('/auth/me/addresses', { method: 'POST', body: JSON.stringify({ label: form.get('label') || 'Home', street: form.get('street'), city: form.get('city'), state: form.get('state'), zipCode: form.get('zipCode'), country: 'India' }) }); setAddresses(data.addresses); event.currentTarget.reset(); setMessage('Address saved') } catch (error) { setMessage(error.message) } finally { setSaving(false) } }; return <main className="content narrow"><button className="back" onClick={back}>← Account</button><Heading eyebrow="SAVED ADDRESSES" title="Your delivery spots" text="Save once, order faster next time." /><div className="address-layout"><form className="payment-panel" onSubmit={save}><label>Label<input name="label" placeholder="Home" /></label><label>Street<input name="street" placeholder="House number and street" required /></label><div className="two"><label>City<input name="city" placeholder="City" required /></label><label>State<input name="state" placeholder="State" /></label></div><label>PIN code<input name="zipCode" placeholder="110001" required /></label><button className="primary">{saving ? 'Saving...' : 'Save address'}</button>{message && <small className="success">{message}</small>}</form><div className="saved-address-list">{addresses.length ? addresses.map((address) => <article key={address._id}><b>{address.label || 'Home'}</b><p>{address.street}, {address.city}</p><small>{address.state} {address.zipCode}</small></article>) : <div className="empty"><h2>No saved addresses</h2><p>Add your first delivery spot.</p></div>}</div></div></main> }
function Favorites({ restaurants, foods, back, openRestaurant, addToCart }) { return <main className="content"><button className="back" onClick={back}>← Account</button><Heading eyebrow="SAVED FOR LATER" title="My favorites" text="The places and dishes you want close by." />{!restaurants.length && !foods.length ? <div className="empty"><h2>Your favorites are waiting</h2><p>Tap the heart on a restaurant to save it here.</p></div> : <><div className="restaurant-grid">{restaurants.map((item) => <RestaurantCard key={idOf(item)} item={item} open={openRestaurant} favorite toggleFavorite={() => {}} />)}</div><div className="food-grid favorite-foods">{foods.map((food) => <FoodCard key={idOf(food)} food={food} add={addToCart} />)}</div></>}</main> }
function HelpSupport({ back }) { return <main className="content narrow"><button className="back" onClick={back}>← Account</button><Heading eyebrow="HELP & SUPPORT" title="We are here to help." text="Find a quick answer or reach the Morsel team." /><div className="support-grid"><article><span>⌁</span><h3>Order support</h3><p>Need help with a late, missing, or incorrect order?</p><button className="text-button" onClick={() => window.location.href = 'mailto:support@morsel.app'}>Email support →</button></article><article><span>?</span><h3>Common questions</h3><p>Delivery times, refunds, coupons, and payment help.</p><button className="text-button" onClick={() => alert('Morsel support is available 9:00 AM to 10:00 PM.')}>View answers →</button></article></div></main> }
