import { useEffect, useMemo, useState } from 'react'
import './App.css'

const configuredApi = import.meta.env.VITE_API_URL || import.meta.env.VITE_API_BASE_URL || ''
const API = configuredApi.replace(/\/+$/, '').replace(/\/api$/, '')
const restaurantsSeed = [
  { id: 'spice-garden', name: 'Spice Garden', cuisine: ['North Indian', 'Biryani'], rating: 4.8, deliveryTime: '25-30 min', image: 'https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&w=1000&q=85', description: 'Comforting Indian classics, slow-cooked and served warm.' },
  { id: 'pizza-hub', name: 'Pizza Hub', cuisine: ['Pizza', 'Italian'], rating: 4.6, deliveryTime: '20-25 min', image: 'https://images.unsplash.com/photo-1574071318508-1cdbab80d002?auto=format&fit=crop&w=1000&q=85', description: 'Wood-fired pizza, handmade pasta and Italian favourites.' },
  { id: 'wok-express', name: 'Wok Express', cuisine: ['Chinese', 'Asian'], rating: 4.5, deliveryTime: '25-35 min', image: 'https://images.unsplash.com/photo-1563379091339-03246963d96c?auto=format&fit=crop&w=1000&q=85', description: 'Wok-tossed noodles, rice and Asian street food.' },
]
const foodsSeed = [
  { id: 'butter-chicken', name: 'Butter Chicken', category: 'North Indian', restaurant: 'Spice Garden', restaurantId: 'spice-garden', price: 349, rating: 4.8, description: 'Creamy tomato gravy with tender chicken.', image: 'https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?auto=format&fit=crop&w=800&q=85' },
  { id: 'paneer', name: 'Paneer Butter Masala', category: 'North Indian', restaurant: 'Spice Garden', restaurantId: 'spice-garden', price: 299, rating: 4.7, description: 'Soft paneer in a rich, creamy gravy.', image: 'https://images.unsplash.com/photo-1631452180519-c014fe946bc7?auto=format&fit=crop&w=800&q=85' },
  { id: 'pizza', name: 'Margherita Pizza', category: 'Pizza', restaurant: 'Pizza Hub', restaurantId: 'pizza-hub', price: 299, rating: 4.7, description: 'Tomato, mozzarella and fresh basil.', image: 'https://images.unsplash.com/photo-1574071318508-1cdbab80d002?auto=format&fit=crop&w=800&q=85' },
  { id: 'noodles', name: 'Veg Hakka Noodles', category: 'Chinese', restaurant: 'Wok Express', restaurantId: 'wok-express', price: 219, rating: 4.6, description: 'Wok-tossed noodles with crisp vegetables.', image: 'https://images.unsplash.com/photo-1612929633738-8fe44f7ec841?auto=format&fit=crop&w=800&q=85' },
]
const idOf = (value) => value?._id || value?.id
const money = (value) => `₹${Math.round(Number(value) || 0)}`
const foodImages = {
  'butter chicken': 'https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?auto=format&fit=crop&w=800&q=85',
  'paneer butter masala': 'https://images.unsplash.com/photo-1631452180519-c014fe946bc7?auto=format&fit=crop&w=800&q=85',
  'margherita pizza': 'https://images.unsplash.com/photo-1574071318508-1cdbab80d002?auto=format&fit=crop&w=800&q=85',
  'veg hakka noodles': 'https://images.unsplash.com/photo-1612929633738-8fe44f7ec841?auto=format&fit=crop&w=800&q=85',
  'classic burger': 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&w=800&q=85',
  'spicy noodles': 'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?auto=format&fit=crop&w=800&q=85',
  'chicken biryani': 'https://images.unsplash.com/photo-1633945274405-b6c8069047b0?auto=format&fit=crop&w=800&q=85',
  'chocolate cake': 'https://images.unsplash.com/photo-1578985545062-69928b1d9587?auto=format&fit=crop&w=800&q=85',
  'green salad bowl': 'https://images.unsplash.com/photo-1540420773420-3366772f4999?auto=format&fit=crop&w=800&q=85',
}
const imageForFood = (food) => (/^https?:\/\//i.test(food.image || '') ? food.image : foodImages[String(food.name || '').trim().toLowerCase()]) || fallbackImage
const fallbackImage = 'data:image/svg+xml,%3Csvg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 800 500"%3E%3Crect width="800" height="500" fill="%23345846"/%3E%3Ccircle cx="400" cy="225" r="92" fill="%23d7ed72"/%3E%3Cpath d="M350 225h100M400 175v100" stroke="%23345846" stroke-width="18" stroke-linecap="round"/%3E%3Ctext x="400" y="390" text-anchor="middle" fill="white" font-family="sans-serif" font-size="30"%3EMorsel%3C/text%3E%3C/svg%3E'
const handleImageError = (event) => { event.currentTarget.onerror = null; event.currentTarget.src = fallbackImage }
async function api(path, options = {}) {
  const token = localStorage.getItem('morsel-token')
  let response
  try {
    response = await fetch(`${API}/api${path}`, { ...options, headers: { 'Content-Type': 'application/json', ...(token ? { Authorization: `Bearer ${token}` } : {}), ...(options.headers || {}) } })
  } catch {
    throw new Error('Cannot connect to the backend. Start it with npm start and try again.')
  }
  const data = await response.json().catch(() => ({}))
  if (!response.ok) throw new Error(data.message || 'Something went wrong')
  return data
}

export default function App() {
  const [view, setView] = useState('home')
  const [restaurants, setRestaurants] = useState(restaurantsSeed)
  const [foods, setFoods] = useState(foodsSeed)
  const [activeRestaurant, setActiveRestaurant] = useState(null)
  const [cart, setCart] = useState(() => JSON.parse(localStorage.getItem('morsel-cart') || '[]'))
  const [user, setUser] = useState(() => JSON.parse(localStorage.getItem('morsel-user') || 'null'))
  const [orders, setOrders] = useState([])
  const [search, setSearch] = useState('')
  const [cuisine, setCuisine] = useState('All')
  const [sort, setSort] = useState('rating')
  const [coupon, setCoupon] = useState('')
  const [couponApplied, setCouponApplied] = useState(false)
  const [authOpen, setAuthOpen] = useState(false)
  const [authMode, setAuthMode] = useState('login')
  const [authBusy, setAuthBusy] = useState(false)
  const [notice, setNotice] = useState('')

  useEffect(() => { localStorage.setItem('morsel-cart', JSON.stringify(cart)) }, [cart])
  useEffect(() => { Promise.all([api('/restaurants'), api('/foods')]).then(([rs, fs]) => { if (rs?.length) setRestaurants(rs); if (fs?.length) setFoods(fs) }).catch(() => {}) }, [])
  useEffect(() => { if (user) api('/orders').then(setOrders).catch(() => {}) }, [user])

  const cuisines = useMemo(() => ['All', ...new Set(restaurants.flatMap((item) => item.cuisine || []))], [restaurants])
  const visibleRestaurants = useMemo(() => restaurants.filter((item) => `${item.name} ${(item.cuisine || []).join(' ')}`.toLowerCase().includes(search.toLowerCase()) && (cuisine === 'All' || item.cuisine?.includes(cuisine))).sort((a, b) => sort === 'rating' ? (b.rating || 0) - (a.rating || 0) : String(a.deliveryTime).localeCompare(String(b.deliveryTime))), [restaurants, search, cuisine, sort])
  const visibleFoods = useMemo(() => foods.filter((item) => `${item.name} ${item.category} ${item.restaurant || ''}`.toLowerCase().includes(search.toLowerCase())), [foods, search])
  const subtotal = cart.reduce((sum, item) => sum + item.price * item.quantity, 0)
  const discount = couponApplied ? Math.min(Math.round(subtotal * (coupon.toUpperCase() === 'FOODIE50' ? .5 : .2)), coupon.toUpperCase() === 'FOODIE50' ? 150 : 100) : 0
  const pricing = { subtotal, discount, delivery: subtotal ? (subtotal >= 499 ? 0 : 40) : 0, platform: subtotal ? 8 : 0, tax: Math.round((subtotal - discount) * .05) }
  pricing.total = pricing.subtotal + pricing.delivery + pricing.platform + pricing.tax - pricing.discount
  const go = (next) => { setView(next); window.scrollTo({ top: 0, behavior: 'smooth' }) }
  const addToCart = (food) => { const foodId = idOf(food); setCart((items) => { const existing = items.find((item) => item.foodId === foodId); return existing ? items.map((item) => item.foodId === foodId ? { ...item, quantity: item.quantity + 1 } : item) : [...items, { foodId, name: food.name, image: food.image, price: Number(food.price), quantity: 1 }] }); setNotice(`${food.name} added to cart`); setTimeout(() => setNotice(''), 1800) }
  const updateQuantity = (foodId, amount) => setCart((items) => items.map((item) => item.foodId === foodId ? { ...item, quantity: item.quantity + amount } : item).filter((item) => item.quantity > 0))
  const openRestaurant = async (item) => { setActiveRestaurant(item); go('restaurant'); try { const data = await api(`/restaurants/${idOf(item)}`); if (data.restaurant) setActiveRestaurant(data.restaurant); if (data.menu?.length) setFoods((current) => [...current.filter((food) => !data.menu.some((entry) => idOf(entry) === idOf(food))), ...data.menu]) } catch {} }
  const signIn = async (event) => { event.preventDefault(); if (authBusy) return; setAuthBusy(true); const form = new FormData(event.currentTarget); try { const data = await api(`/auth/${authMode}`, { method: 'POST', body: JSON.stringify(Object.fromEntries(form)) }); localStorage.setItem('morsel-token', data.token); localStorage.setItem('morsel-user', JSON.stringify(data.user)); setUser(data.user); setAuthOpen(false); setNotice(`Welcome, ${data.user.name}`) } catch (error) { setNotice(error.message) } finally { setAuthBusy(false) } }
  const placeOrder = async (event) => { event.preventDefault(); if (!user) return setAuthOpen(true); const form = new FormData(event.currentTarget); const paymentMethod = form.get('paymentMethod'); const payload = { items: cart.map((item) => ({ foodId: item.foodId, quantity: item.quantity })), deliveryAddress: { street: form.get('street'), city: form.get('city'), state: form.get('state'), zipCode: form.get('zipCode'), country: 'India' }, phone: form.get('phone'), notes: form.get('notes'), paymentMethod, couponCode: couponApplied ? coupon.toUpperCase() : '' }; const finish = (order) => { setCart([]); setOrders((current) => [order, ...current]); go('orders'); setNotice('Order placed successfully') }; try { const order = await api('/orders', { method: 'POST', body: JSON.stringify(payload) }); const paymentData = await api('/payments/create', { method: 'POST', body: JSON.stringify({ orderId: order._id, provider: paymentMethod === 'cash' ? 'cash' : 'razorpay' }) }); if (paymentMethod === 'cash') return finish(order); if (!paymentData.razorpayOrder || !paymentData.keyId) throw new Error('Online payment is not configured'); await new Promise((resolve, reject) => { const script = document.createElement('script'); script.src = 'https://checkout.razorpay.com/v1/checkout.js'; script.onload = resolve; script.onerror = () => reject(new Error('Unable to load Razorpay')); document.body.appendChild(script) }); const checkout = new window.Razorpay({ key: paymentData.keyId, amount: paymentData.razorpayOrder.amount, currency: 'INR', name: 'Morsel', description: 'Morsel food order', order_id: paymentData.razorpayOrder.id, prefill: { name: user.name, email: user.email, contact: payload.phone }, handler: async (response) => { try { await api(`/payments/${paymentData.payment._id}/verify`, { method: 'POST', body: JSON.stringify(response) }); finish(order) } catch (error) { setNotice(error.message) } } }); checkout.open() } catch (error) { setNotice(error.message) } }

  return <div className="app"><header className="topbar"><button className="brand" onClick={() => go('home')}><span className="brand-mark">M</span><span><b>Morsel</b><small>good food, good mood</small></span></button><div className="search"><span>⌕</span><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search restaurants or dishes" /></div><nav><button onClick={() => go('restaurants')}>Restaurants</button><button onClick={() => go('orders')}>Orders</button><button onClick={() => user ? go('profile') : setAuthOpen(true)}>{user ? user.name : 'Sign in'}</button><button className="cart-link" onClick={() => go('cart')}>Cart <b>{cart.reduce((sum, item) => sum + item.quantity, 0)}</b></button></nav></header>
    {notice && <div className="toast">{notice}</div>}
    {view === 'home' && <Home onRestaurants={() => go('restaurants')} restaurants={restaurants} foods={foods} openRestaurant={openRestaurant} addToCart={addToCart} />}
    {view === 'restaurants' && <main className="content"><Heading eyebrow="DISCOVER" title="Restaurants near you" text={`${visibleRestaurants.length} places serving your favourites`} /><div className="filters"><select value={sort} onChange={(event) => setSort(event.target.value)}><option value="rating">Top rated</option><option value="delivery">Fastest delivery</option></select>{cuisines.map((item) => <button className={cuisine === item ? 'active' : ''} key={item} onClick={() => setCuisine(item)}>{item}</button>)}</div><div className="restaurant-grid">{visibleRestaurants.map((item) => <RestaurantCard key={idOf(item)} item={item} open={openRestaurant} />)}</div></main>}
    {view === 'restaurant' && activeRestaurant && <RestaurantDetail item={activeRestaurant} foods={foods.filter((food) => String(food.restaurantId) === String(idOf(activeRestaurant)) || food.restaurant === activeRestaurant.name)} addToCart={addToCart} back={() => go('restaurants')} />}
    {view === 'cart' && <Cart cart={cart} update={updateQuantity} coupon={coupon} setCoupon={setCoupon} apply={() => setCouponApplied(['FOODIE50', 'WELCOME'].includes(coupon.toUpperCase()))} applied={couponApplied} pricing={pricing} checkout={() => go('checkout')} />}
    {view === 'checkout' && <Checkout user={user} placeOrder={placeOrder} pricing={pricing} />}
    {view === 'orders' && <Orders orders={orders} signIn={() => setAuthOpen(true)} />}
    {view === 'profile' && <Profile user={user} logout={() => { localStorage.clear(); setUser(null); go('home') }} />}
    <footer><b>Morsel</b><span>Thoughtful food, delivered with care.</span><span>© 2026 Morsel</span></footer>
    {authOpen && <div className="modal" onClick={() => setAuthOpen(false)}><form className="auth-card" onClick={(event) => event.stopPropagation()} onSubmit={signIn}><button type="button" className="close" onClick={() => setAuthOpen(false)}>×</button><span className="eyebrow">{authMode === 'login' ? 'WELCOME BACK' : 'JOIN MORSEL'}</span><h2>{authMode === 'login' ? 'Sign in to order' : 'Create your account'}</h2>{authMode === 'register' && <input name="name" placeholder="Full name" required />}{authMode === 'register' && <input name="phone" placeholder="Phone number" required />}<input name="email" type="email" placeholder="Email address" required /><input name="password" type="password" placeholder="Password" minLength="6" required /><button className="primary" disabled={authBusy}>{authBusy ? 'Please wait...' : authMode === 'login' ? 'Sign in' : 'Create account'}</button><p>{authMode === 'login' ? 'New to Morsel?' : 'Already have an account?'} <button type="button" className="text-button" onClick={() => setAuthMode(authMode === 'login' ? 'register' : 'login')}>{authMode === 'login' ? 'Register' : 'Sign in'}</button></p></form></div>}
  </div>
}

function Heading({ eyebrow, title, text }) { return <div className="heading"><span className="eyebrow">{eyebrow}</span><h1>{title}</h1><p>{text}</p></div> }
function Home({ onRestaurants, restaurants, foods, openRestaurant, addToCart }) { return <main><section className="hero"><div><span className="eyebrow">A BETTER WAY TO EAT</span><h1>Good food finds<br /><i>you.</i></h1><p>Discover local kitchens, thoughtful menus and the comfort of dinner arriving at your door.</p><button className="primary" onClick={onRestaurants}>Explore restaurants <span>→</span></button></div><div className="hero-art"><img src="https://images.unsplash.com/photo-1504674900247-0877df9cc836?auto=format&fit=crop&w=1200&q=85" alt="A table full of food" onError={handleImageError} /><div className="hero-food-stack">{foods.slice(0, 3).map((food, index) => <div className={`hero-food hero-food-${index}`} key={idOf(food)}><img src={imageForFood(food)} alt={food.name} onError={handleImageError} /><span>{food.name}</span></div>)}</div></div></section><section className="content"><Heading eyebrow="LOCAL FAVOURITES" title="Made for your mood" text="A few places we think you'll love." /><div className="restaurant-grid">{restaurants.slice(0, 3).map((item) => <RestaurantCard key={idOf(item)} item={item} open={openRestaurant} />)}</div><div className="section-head"><div><span className="eyebrow">QUICK BITES</span><h2>Popular right now</h2></div><button className="text-button" onClick={onRestaurants}>See all →</button></div><div className="food-grid">{foods.slice(0, 4).map((food) => <FoodCard key={idOf(food)} food={food} add={addToCart} />)}</div></section></main> }
function RestaurantCard({ item, open }) { return <article className="restaurant-card" onClick={() => open(item)}><img src={item.image} alt={item.name} onError={handleImageError} /><div><div className="card-line"><h3>{item.name}</h3><span className="rating">★ {Number(item.rating || 0).toFixed(1)}</span></div><p>{(item.cuisine || []).join(' · ')}</p><small>{item.deliveryTime || '30 min'} · delivers to you</small></div></article> }
function FoodCard({ food, add }) { return <article className="food-card"><img src={imageForFood(food)} alt={food.name} onError={handleImageError} /><div><div className="card-line"><h3>{food.name}</h3><span className="rating">★ {Number(food.rating || 0).toFixed(1)}</span></div><p>{food.description}</p><div className="food-bottom"><strong>{money(food.price)}</strong><button onClick={() => add(food)}>Add</button></div></div></article> }
function RestaurantDetail({ item, foods, addToCart, back }) { return <main className="content"><button className="back" onClick={back}>← All restaurants</button><section className="detail-hero"><img src={item.image} alt={item.name} onError={handleImageError} /><div><span className="eyebrow">{(item.cuisine || []).join(' · ').toUpperCase()}</span><h1>{item.name}</h1><p>{item.description || 'Made fresh, just for you.'}</p><span className="rating">★ {Number(item.rating || 0).toFixed(1)} · {item.deliveryTime || '30 min'}</span></div></section><div className="section-head"><div><span className="eyebrow">THE MENU</span><h2>Choose your comfort</h2></div></div><div className="food-grid">{foods.map((food) => <FoodCard key={idOf(food)} food={food} add={addToCart} />)}</div></main> }
function Bill({ pricing }) { return <div className="bill"><h3>Order summary</h3><p><span>Item total</span><b>{money(pricing.subtotal)}</b></p><p><span>Delivery</span><b>{pricing.delivery ? money(pricing.delivery) : 'FREE'}</b></p><p><span>Platform fee</span><b>{money(pricing.platform)}</b></p><p><span>Taxes</span><b>{money(pricing.tax)}</b></p>{pricing.discount > 0 && <p className="discount"><span>Coupon discount</span><b>-{money(pricing.discount)}</b></p>}<div className="total"><span>To pay</span><strong>{money(pricing.total)}</strong></div></div> }
function Cart({ cart, update, coupon, setCoupon, apply, applied, pricing, checkout }) { return <main className="content narrow"><Heading eyebrow="YOUR ORDER" title="Your cart" text={`${cart.length} ${cart.length === 1 ? 'item' : 'items'} selected`} />{cart.length === 0 ? <div className="empty"><span>◌</span><h2>Your cart is waiting</h2><p>Add something delicious to get started.</p></div> : <div className="cart-layout"><div>{cart.map((item) => <div className="cart-row" key={item.foodId}><img src={imageForFood(item)} alt={item.name} onError={handleImageError} /><div><h3>{item.name}</h3><strong>{money(item.price)}</strong></div><div className="quantity"><button onClick={() => update(item.foodId, -1)}>−</button><span>{item.quantity}</span><button onClick={() => update(item.foodId, 1)}>+</button></div></div>)}<div className="coupon"><input value={coupon} onChange={(event) => setCoupon(event.target.value)} placeholder="Coupon code" /><button onClick={apply}>Apply</button></div>{applied && <small className="success">Coupon applied. Nice choice.</small>}</div><div><Bill pricing={pricing} /><button className="primary wide" onClick={checkout}>Continue to checkout <span>→</span></button></div></div>}</main> }
function Checkout({ user, placeOrder, pricing }) { return <main className="content narrow"><Heading eyebrow="CHECKOUT" title="Almost there." text="Where should we bring your order?" /><form className="checkout-layout" onSubmit={placeOrder}><div className="checkout-form"><label>Phone number<input name="phone" defaultValue={user?.phone || ''} required /></label><label>Address<input name="street" placeholder="House number and street" required /></label><div className="two"><label>City<input name="city" placeholder="City" required /></label><label>State<input name="state" placeholder="State" required /></label></div><div className="two"><label>PIN code<input name="zipCode" placeholder="110001" required /></label><label>Instructions<input name="notes" placeholder="Ring the bell, leave at door..." /></label></div><fieldset><legend>Payment method</legend><label className="payment"><input type="radio" name="paymentMethod" value="cash" defaultChecked /> Cash on Delivery</label><label className="payment"><input type="radio" name="paymentMethod" value="razorpay" /> Razorpay online payment</label></fieldset><button className="primary wide">Place order <span>{money(pricing.total)} →</span></button></div><Bill pricing={pricing} /></form></main> }
function Orders({ orders, signIn }) { return <main className="content narrow"><Heading eyebrow="YOUR JOURNEY" title="Order history" text="Every good meal has a story." />{!orders.length ? <div className="empty"><h2>No orders yet</h2><p>Once you order, your meals will appear here.</p><button className="primary" onClick={signIn}>Sign in to see orders</button></div> : <div className="orders">{orders.map((order) => <article key={order._id}><div><span className="eyebrow">{new Date(order.createdAt).toLocaleDateString()}</span><h3>{order.items?.map((item) => `${item.name} ×${item.quantity}`).join(', ')}</h3></div><strong>{money(order.totalAmount)}</strong><span className="status">{order.status}</span></article>)}</div>}</main> }
function Profile({ user, logout }) { return <main className="content narrow"><Heading eyebrow="ACCOUNT" title="Your profile" text="Your details, kept in one place." /><div className="profile"><span className="avatar">{user?.name?.[0] || 'M'}</span><h2>{user?.name || 'Morsel member'}</h2><p>{user?.email}</p><p>{user?.phone || 'Add a phone number at checkout.'}</p><button className="text-button" onClick={logout}>Sign out</button></div></main> }
